### PR TITLE
fix: make dependencies and other build arguments static

### PR DESCRIPTION
**Pull request by ohjunseung**
I tried to install version 1.0.3 with pip and it doesn't install the dependencies. Figured out that requirements.txt is not included in the [source distribution](https://files.pythonhosted.org/packages/11/97/9e9f22b9276cd1631592b0453a1ebef6e7b77df8b3c129e6fca17ce7d39a/table2ascii-1.0.3.tar.gz), hence giving the install_requires an empty array. I assume this doesn't happen on 1.0.1 because it has a [wheel file](https://files.pythonhosted.org/packages/08/47/695175b33d4d9ba1db451bf3f9d0d8e9daa0ff5b7541edba0587ab25cd21/table2ascii-1.0.1-py3-none-any.whl).

So, I thought that making the dependencies explicit is better.

References:
[same issue with wheel](https://stackoverflow.com/questions/58881683/pip-does-not-install-my-package-dependencies)

### CODE REVIEW

**Comment by DenverCoder1** [comment]
Thanks for bringing up the issue.

I don't think the dependencies should be repeated in two places, though.

I think instead the dependencies can be listed in `pyproject.toml` and removed from the `setup.py` (and `requirement.txt` can be deleted).

https://peps.python.org/pep-0631/#specification

The ideal solution would probably be for everything in `setup.py` to be replaced with a `pyproject.toml` alternative.

**Comment by ohjunseung** [comment]
I'm not that familiar with pip build system. From your suggestion, this fc3aadfb024bc5a64c8603d931bc841530d076cd might be good for now.

**Comment by DenverCoder1** [comment]
Thanks for your help on the issue, I hope it's fine with you if I add to this PR some additional static attributes

**Review by DenverCoder1 — APPROVED** [review]

**Comment by DenverCoder1** [comment]
Just tested with 1.0.4 and it looks good to me :tada:

**Pull request merged**
